server:
  port: ${SERVER_PORT:6312}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:10.1.1.101}:${DATASOURCE_PORT:3306}/${DATASOURCE_TARGET:zq_data_sync}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: ${DATASOURCE_USERNAME:cxdev}
    password: ${DATASOURCE_PASSWORD:123456}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      auto-commit: true
      pool-name: Hikari Pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: Select 1
